branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Not really necessary, just to get a green badge on “master”
    - master
language: rust
os: linux
dist: xenial
addons:
  apt:
    sources:
    - sourceline: "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-11 main"
      key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    packages:
    - llvm-3.9-dev
    - libclang-3.9-dev
    - clang-3.9
    - clang-11
    - cmake
    - qemu-user
rust:
   - stable
   - beta
   - nightly
   - nightly-2021-03-25
env:
  jobs:
    # Matrix build of 3 targets against the above rust toolchain releases
    - TARGET=aarch64-unknown-linux-musl
    - TARGET=x86_64-fortanix-unknown-sgx
    - TARGET=x86_64-unknown-linux-gnu ZLIB_INSTALLED=true AES_NI_SUPPORT=true
  global:
    - RUST_BACKTRACE=1
    # Pinned to this particular nightly version because of core_io. This can be
    # re-pinned whenever core_io is updated to the latest nightly.
    - CORE_IO_NIGHTLY=nightly-2021-03-25
    - LLVM_CONFIG_PATH=llvm-config-3.9

before_script:
  - if [ "$TARGET" == "aarch64-unknown-linux-musl" ]; then
      cd /tmp && wget https://musl.cc/aarch64-linux-musl-cross.tgz;
      tar -xvzf aarch64-linux-musl-cross.tgz;
      cd $TRAVIS_BUILD_DIR;
    fi

script:
  - ./ct.sh
